RNGPools = {"Beasts": [StonetuskBoar, BloodfenRaptor, RiverCrocolisk, IronfurGrizzly, SilverbackPatriarch, OasisSnapjaw, CoreHound, TimberWolf, StarvingBuzzard, TundraRhino, 
				AngryChicken, HungryCrab, YoungDragonhawk, DireWolfAlpha, EmperorCobra, IronbeakOwl, JunglePanther, KingMukla, StampedingKodo, StranglethornTiger, 
				TheBeast, ScavengingHyena, SavannahHighmane, KingCrush, ],
		"Mage Spells": [ArcaneMissiles, MirrorImage, ArcaneExplosion, Frostbolt, ArcaneIntellect, FrostNova, Fireball, Polymorph, Flamestrike, TomeofIntellect, 
				Icicle, Counterspell, IceBarrier, MirrorEntity, Spellbender, Vaporize, ConeofCold, Blizzard, Pyroblast, ],
		"Class Cards except Druid": [ArcaneMissiles, MirrorImage, ArcaneExplosion, Frostbolt, ArcaneIntellect, FrostNova, Fireball, Polymorph, WaterElemental, Flamestrike, 
				TomeofIntellect, Icicle, ManaWyrm, SorcerersApprentice, Counterspell, IceBarrier, MirrorEntity, Spellbender, Vaporize, KirinTorMage, 
				ConeofCold, EtherealArcanist, Blizzard, ArchmageAntonidas, Pyroblast, ],
		"Class Cards except Mage": [ArcaneShot, TimberWolf, Tracking, HuntersMark, AnimalCompanion, KillCommand, Houndmaster, MultiShot, StarvingBuzzard, TundraRhino, 
				BestialWrath, ExplosiveTrap, FreezingTrap, Misdirection, SnakeTrap, Snipe, Flare, ScavengingHyena, DeadlyShot, EaglehornBow, 
				UnleashtheHounds, ExplosiveShot, SavannahHighmane, GladiatorsLongbow, KingCrush, ],
		"Class Cards except Hunter": [BlessingofMight, HandofProtection, Humility, LightsJustice, HolyLight, BlessingofKings, Consecration, HammerofWrath, TruesilverChampion, GuardianofKings, 
				BlessingofWisdom, EyeforanEye, SacredSacrifice, Redemption, Repentence, ArgentProtector, Equality, ArdorPeacekeeper, SwordofJustice, BlessedChampion, 
				HolyWrath, Righteousness, AvengingWrath, LayonHands, TirionFordring, ],
		"Class Cards except Paladin": [HolySmite, MindVision, NorthshireCleric, PowerWordShield, Radiance, DivineSpirit, ShadowWordPain, ShadowWordDeath, HolyNova, MindControl, 
				CircleofHealing, Silence, InnerFire, Lightwell, Shadowform, Thoughtsteal, AuchenaiSoulpriest, Lightspawn, MassDispel, Mindgames, 
				ShadowMadness, CabalShadowPriest, HolyFire, TempleEnforcer, ProphetVelen, ],
		"Class Cards except Priest": [Backstab, DeadlyPoison, SinisterStrike, Sap, Shiv, FanofKnives, Plaguebringer, Assassinate, AssassinsBlade, Sprint, 
				Preparation, Shadowstep, Pilfer, Betrayal, ColdBlood, DefiasRingleader, Eviscerate, PatientAssassin, EdwinVancleef, Headcrack, 
				PerditionsBlade, SI7Agent, BladeFlurry, MasterofDisguise, Kidnapper, ],
		"Class Cards except Rogue": [AncestralHealing, TotemicMight, FrostShock, RockbiterWeapon, Windfury, FlametongueTotem, Hex, Windspeaker, Bloodlust, FireElemental, 
				DustDevil, EarthShock, ForkedLightning, LightningBolt, AncestralSpirit, StormforgedAxe, FarSight, FeralSpirit, LavaBurst, LightningStorm, 
				ManaTideTotem, UnboundElemental, Doomhammer, EarthElemental, AlAkirtheWindlord, ],
		"Class Cards except Shaman": [SacrificialPact, Corruption, MortalCoil, Soulfire, Voidwalker, Felstalker, DrainLife, ShadowBolt, Hellfire, DreadInfernal, 
				BloodImp, CalloftheVoid, FlameImp, Demonfire, SenseDemon, SummoningPortal, Felguard, VoidTerror, PitLord, Shadowflame, 
				BaneofDoom, SiphonSoul, Siegebreaker, TwistingNether, LordJaraxxus, ],
		"Class Cards except Warlock": [Whirlwind, Charge, Execute, Cleave, HeroicStrike, FieryWarAxe, ShieldBlock, WarsongCommander, KorkronElite, ArcaniteReaper, 
				InnerRage, ShieldSlam, Upgrade, Armorsmith, BattleRage, CommandingShout, CruelTaskmaster, Rampage, Slam, FrothingBerserker, 
				ArathiWeaponsmith, MortalStrike, Brawl, Gorehowl, GrommashHellscream, ],
		"Class Cards except Warrior": [Innervate, Moonfire, Claw, MarkoftheWild, HealingTouch, SavageRoar, WildGrowth, Swipe, Starfire, IronbarkProtector, 
				Savagery, PoweroftheWild, Wrath, MarkofNature, Bite, KeeperoftheGrove, SouloftheForest, DruidoftheClaw, ForceofNature, Starfall, 
				Nourish, AncientofLore, AncientofWar, GiftoftheWild, Cenarius, ],
		"Class Cards except Neutral": [ArcaneShot, TimberWolf, Tracking, HuntersMark, AnimalCompanion, KillCommand, Houndmaster, MultiShot, StarvingBuzzard, TundraRhino, 
				BestialWrath, ExplosiveTrap, FreezingTrap, Misdirection, SnakeTrap, Snipe, Flare, ScavengingHyena, DeadlyShot, EaglehornBow, 
				UnleashtheHounds, ExplosiveShot, SavannahHighmane, GladiatorsLongbow, KingCrush, ],
		"Demons": [Voidwalker, Felstalker, DreadInfernal, IllidanStormrage, BloodImp, FlameImp, Felguard, VoidTerror, PitLord, Siegebreaker, 
				LordJaraxxus, ],
		}